version: '3.8'

services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      RACK_ENV: development
      DB_ADAPTER: ${DB_ADAPTER:-sqlite3}
      DB_HOST: ${DB_HOST:-localhost}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME:-majin_devel.sqlite3}
    depends_on:
      - postgres
      - mariadb

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: majin_devel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: majin_devel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  postgres_data:
  mariadb_data:
