default: &default
  adapter: sqlite3

development:
  <<: *default
  database: 'majin_devel.sqlite3'

test:
  <<: *default
  database: 'majin_test.sqlite3'

production:
  <<: *default
  database: 'majin.sqlite3'
